# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_sub',
            name='starting_price',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
