# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_lot_sub_starting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_sub',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
