# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 07:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0005_lot_sub_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.BigIntegerField()),
                ('lot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Lot_sub')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
