# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auto_20170612_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot_sub',
            name='winner',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
