# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0008_auto_20170612_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='lot_sub',
            name='winner',
        ),
        migrations.AddField(
            model_name='winner',
            name='lot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Lot_sub'),
        ),
        migrations.AddField(
            model_name='winner',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
