# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auto_20170612_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.LotRate'),
        ),
    ]
