# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0010_auto_20170612_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='participant',
        ),
        migrations.AddField(
            model_name='winner',
            name='winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
