# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_auto_20170612_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='lot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Lot_sub'),
        ),
    ]
