# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_auto_20170612_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_sub',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
