# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_lot_sub_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot_sub',
            name='image',
        ),
    ]
