# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0018_lot_sub_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='userph/'),
        ),
        migrations.AlterField(
            model_name='lot_sub',
            name='image',
            field=models.ImageField(null=True, upload_to='lotph/'),
        ),
    ]
